"""add verify hash and dispensed fields

Revision ID: 64868781b49f
Revises: 4514dae22e96
Create Date: 2026-06-15 06:40:43.719219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64868781b49f'
down_revision: Union[str, Sequence[str], None] = '4514dae22e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('verify_hash', sa.String(), nullable=True))
    op.add_column('consultations', sa.Column('is_dispensed', sa.Boolean(), nullable=True))
    op.add_column('consultations', sa.Column('dispensed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_consultations_verify_hash'), 'consultations', ['verify_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_verify_hash'), table_name='consultations')
    op.drop_column('consultations', 'dispensed_at')
    op.drop_column('consultations', 'is_dispensed')
    op.drop_column('consultations', 'verify_hash')
    # ### end Alembic commands ###
