"""add is_voided field

Revision ID: e627e67cb329
Revises: 896cbc579dc8
Create Date: 2026-06-15 16:52:45.077598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e627e67cb329'
down_revision: Union[str, Sequence[str], None] = '896cbc579dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('is_voided', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'is_voided')
    # ### end Alembic commands ###
